### ISSUE TITLE
CocoaPods could not find compatible versions for pod "WhatsNewKit"

### ISSUE THREAD

**Issue by saldous** [SvenTiigi/WhatsNewKit#12]
Can't install via cocoapods, xcode 10.1

**Comment by saldous** [comment]
Looks like it needs min iOS 10 deployment target, won't work with 9.0

**Comment by SvenTiigi** [comment]
Hey @saldous 

Yes the minimum deployment target is set to iOS 10.0 because `WhatsNewKit` is supporting the HapticFeedback API via the [UIFeedbackGenerator](https://developer.apple.com/documentation/uikit/uifeedbackgenerator) API.

But the good news is that I've found an easy solution to drop the deployment target to iOS 9.0 while breaking non existing API's.

The feature branch [ios-9-deployment-target](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/ios-9-deployment-target) contains those changes. You can integrate and test this feature branch in your Project with CocoaPods:

```ruby
pod 'WhatsNewKit', :git => 'https://github.com/SvenTiigi/WhatsNewKit.git', :branch => 'ios-9-deployment-target'
```

Of course this is the first attempt and some progress needs to be done on this feature-branch before it will be merged in the `develop` branch. But I hope this quick solution might help you 🙌

**Comment by saldous** [comment]
I appreciate the effort. I just ran a report to see how many of my users are on iOS 9, it was only 93, so I decided to drop support for it and make the min. 10.0 now anyway.
