### ISSUE TITLE
Using a custom button as completion button

### ISSUE THREAD

**Issue by vince-carpino** [SvenTiigi/WhatsNewKit#19]
Throughout my app, I've utilized [FlatUIKit](https://github.com/Grouper/FlatUIKit#buttons)'s `FUIButton`.

Is it possible to use a custom button such as this as the completion button?

**Comment by SvenTiigi** [comment]
Hey @vince-carpino,

Currently `WhatsNewKit` doesn't support this feature.

In order to allow customizing the Buttons to a special style I would propose a customization closure which would be available on the `DetailButton` and `CompletionButton` configuration struct.

```swift
var configuration = WhatsNewViewController.Configuration()

configuration.detailButton.customization = { button in
    // TODO: Configure the DetailButton
}

configuration.completionButton.customization = { button in
    // TODO: Configure the CompletionButton
}
```

I've already implemented this API on the [`feature/button-customization`](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/button-customization) Branch. Please let me know if this change fits your needs.

**Comment by vince-carpino** [comment]
Thanks for your quick reply.

I tried your suggestion but I don't think that what I'm looking for is possible, at least as far as my rather limited iOS development knowledge allows. I don't think Cocoapods have the ability to use each others libraries, which I believe is what I would need in order to make this work.

Please let me know if I'm wrong.

**Comment by SvenTiigi** [comment]
Hey @vince-carpino,

The intent of the `customization` closure is to post configure / customize the `DetailButton` or `CompletionButton` to your needs. For example you could apply the same effects to the Button as `FlatUIKit` does with its [`FUIButton`](https://github.com/Grouper/FlatUIKit/blob/63fea9a86cadb2180173e29bf75fa978ec999fc6/Classes/ios/FUIButton.m#L81).

Of course it would be easier for you if you could simply pass in a pre-initialized `UIButton` instance. Implementing this kind of API would lead to some breaking changes which would be better placed in an upcoming `2.0` version of `WhatsNewKit`.

**Comment by SvenTiigi** [comment]
Closing due inactivity. Feel free to re-open the issue at any time.
