### ISSUE TITLE
`import: WhatsNewKit`

### ISSUE THREAD

**Issue by AlexFlume** [SvenTiigi/WhatsNewKit#22]
## WhatsNewKit Environment

- WhatsNewKit version: 1.1.9
- Xcode version: 10.2.1
- Swift version: 5
- macOS version running Xcode: 10.14.5
- Dependency manager (Carthage, CocoaPods, Manually):  CocoaPods

## What did you do?

I added `pod 'WhatsNewKit'` to the my Xcode project and successfully installed WhatsNewKit.

## What did you expect to happen?

I expected to be able to type `import: WhatsNewKit` in the AppDelegate.swift file.

## What happened instead?

When I type `import: WhatsNewKit` in the AppDelegate.swift file the framework isn't recognised and I get a "No such module 'WhatsNewKit'" warning in red. - I can see the pods file has been added, but Xcode isn't letting me use it.

I'm a first-time developer so could be missing something obvious, but I'm doing everything shown in the instructions (and a YouTube video I found online) but Xcode just can't see the WhatsNewKit framework.

Any help would be much appreciated this looks amazing.

**Comment by SvenTiigi** [comment]
Hey @AlexFlume,

thanks for your detailed bug report.

Please run `pod install` inside your project directory via the Terminal after you have added `pod 'WhatsNewKit'` to your Podfile.

After `pod install` has completed successfully open your Xcode project and make a `Clean-Build`. 

In your `AppDelegate.swift` file you should be able to import WhatsNewKit without any error:

```swift
import UIKit
import WhatsNewKit

...
```

Otherwise run `pod deintegrate && pod install` inside your project directory via the Terminal.

**Comment by AlexFlume** [comment]
Thank you, Sven.

Does this have to be done via the Terminal, or can it be done via the CocoaPods Mac app?

**Comment by SvenTiigi** [comment]
Hey @AlexFlume,

Just to be sure you should run the commands via your `Terminal` 👌

**Comment by SvenTiigi** [comment]
Closing due inactivity. Feel free to re-open the issue at any time.
