### ISSUE TITLE
Page indicator

### ISSUE THREAD

**Issue by Pe-te** [SvenTiigi/WhatsNewKit#3]
Hi, very nice library. Is there a way to show a page indicator in the slides?

**Comment by SvenTiigi** [comment]
Hey @Pe-te,

Thanks for your appreciation 🙌

Could you explain your issue / feature-request in detail?

Currently the visible `Features` aka. `WhatsNew.Item` are visualized in a `UITableView` and can only been scrolled vertically. There is currently no horizontal scrolling available which would open the need of a `PageIndicator`.

**Comment by Pe-te** [comment]
Oh okay, maybe I misunderstood the animation on the github page? It's just showing the different designs? It looked like it swipes from one page to the next.

We want to show multiple slides, each with a tableview and the user should be able to swipe between the slides, both forward and backwards.

**Comment by SvenTiigi** [comment]
Yes the example `GIF` just showing different designs of a `WhatsNewViewController` which were pushed via a `UINavigationController` during screen recording.

If I understood your correctly you want to change the scrolling behaviour of the `UITableView` where your new Features are visualized from vertical to horizontal. To do so the `UITableView` should be refactored to a `UICollectionView` in order to manipulate the layout.

Or you can simply put multiple `WhatsNewViewController`s into a `UIPageViewController` in order to swipe between multiple pages.

**Comment by Pe-te** [comment]
> Or you can simply put multiple WhatsNewViewControllers into a UIPageViewController in order to swipe between multiple pages.

Yes, that's what we are after, from the animation it just looked like it already does it. I'll give it a try, thanks!

**Comment by SvenTiigi** [comment]
Feel free to open a PR to extend `WhatsNewKit` 🙌
