### ISSUE TITLE
Swipe gesture to dismiss doesn't work reliably

### ISSUE THREAD

**Issue by francosolerio** [SvenTiigi/WhatsNewKit#44]
## WhatsNewKit Environment

- WhatsNewKit version: 1.3.5
- Xcode version: 11.6
- Swift version: 5
- macOS version running Xcode: 10.15.5
- Dependency manager (SPM, Carthage, CocoaPods, Manually): SPM or standalone

## What did you do?

Build and run WhatsNewKit-Example

Tap "Present" button

Put finger on the ItemsView and drag down

## What did you expect to happen?

The WhatsNew panel should begin dismiss animation and follow the finger's movement

## What happened instead?

The WhatsNew panel doesn't move at all 90% of the times. Sometimes it begins moving late after the gesture has moved a considerable amount of space. Rarely it begins immediately and follows the gesture.

**Comment by francosolerio** [comment]
Personal consideration: Swipe to dismiss is handled automatically when a modally presented panel contains a UITableViewController subclass. Maybe using a UIViewController subclass containing a UITableView for ItemsView needs the same behavior to be coded manually with some `UIGestureRecognizerDelegate` method.

**Comment by SvenTiigi** [comment]
Hey @francosolerio,

Thanks for your bug report 🙌

It seems like that the following line of code causes the issue (`WhatsNewItemsViewController.swift`):

```swift
tableView.alwaysBounceVertical = false
```

When the contentSize of the TableView doesn't exceed the size of the frame the TableView will ignore the scroll gesture and therefore it will be not passed down to the responder chain in order to allow iOS to listen to the scroll gesture.

Please check out the [`develop`](https://github.com/SvenTiigi/WhatsNewKit/tree/develop) branch and check if the problem still exists.

**Comment by francosolerio** [comment]
Thank you @SvenTiigi,
 I can confirm the issue is resolved on the develop branch.

**Comment by SvenTiigi** [comment]
Hey @francosolerio,

Just wanted to let you know that this bug fix is now available within the latest release [1.3.6](https://github.com/SvenTiigi/WhatsNewKit/releases/tag/1.3.6)

**Comment by francosolerio** [comment]
Very good, thank you Sven!
