### ISSUE TITLE
[iPad] Default primary action does not dismiss the WhatsNewViewController

### ISSUE THREAD

**Issue by john-work-ios** [SvenTiigi/WhatsNewKit#58]
## WhatsNewKit Environment

- WhatsNewKit version: 2.0.2 **using UIKit**
- Xcode version: 13.3
- Swift version: 5+
- macOS version running Xcode: 12.4
- Dependency manager (SPM, Manually): SPM

## What did you do?

on iPad, the continue button (primary action) does not dismiss. Works fine on iPhone.

## What did you expect to happen?

The WhatsNewVC should dismiss

## What happened instead?

As a workaround, I used the 'onDismiss' completion to dismiss the controller

**Comment by SvenTiigi** [comment]
Hi @john-work-ios,

Sorry for the late reply. 
I have successfully reproduced the bug and I'm currently investigating this issue.
I will let you know when a new version is available which fixes this problem ✌️

**Comment by aehlke** [comment]
any lead on this from your investigation if we'd like to support on a fix?

**Comment by SvenTiigi** [comment]
Hi @john-work-ios,

I've recently tried to reproduce the bug and it seems like this issue has been fixed with either iOS 15 or iOS 16.
Seems like UIKit now passes a correct context for the [`PresentationMode`](https://developer.apple.com/documentation/swiftui/presentationmode) which is called when the primary action gets tapped in order to dismiss the sheet / presented view controller.

https://github.com/SvenTiigi/WhatsNewKit/blob/641b2f5e771627d172f69ebfc5dda777ee74393d/Sources/View/WhatsNewView.swift#L215-L224

https://user-images.githubusercontent.com/11733014/222533689-b3e76139-8212-45c2-8602-a97fd0950421.mov

**Comment by SvenTiigi** [comment]
Closing due inactivity.
Please feel free to re-open the issue at any time.
